php:
  preset: laravel
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
      - server.php
# multiple languages is a pro feature
# js:
#   finder:
#     not-name:
#       - webpack.mix.js
# css: true
